# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d7dda33e0cef88dcd2c70cb983889cd8c27ed65f8e0a095a0e4a9432538f56ca691bc085c7a337caed4f4b2667eeb29d0fbc0d23639e747589e0d6c59e8e51d

test:
  secret_key_base: faa0e9ae18cef2c9bb44cc1f6e99c16215c85151ebccbca5123ce5475a8e6c05bfb15c6c18c071d2eee78223694bbeeae56e69268190ad2804f67a270a1c39c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
